#!/bin/bash

case $BLOCK_BUTTON in
    4)
        light -A 5
        ;;
    5)
        light -U 5
        ;;
    6)
        light -A 1
        ;;
    7)
        light -U 1
        ;;
esac

l_value=$(light | sed -r 's/\..+//')

if (( $l_value > 99 )); then
    echo ""
elif (( $l_value > 0 )); then
    echo "<span size='x-small'>${l_value}</span>"
else
    echo ""
fi

if [ "$1" -eq "$1" ] 2>/dev/null
   then
    pkill -RTMIN+$1 i3block
fi
