#!/usr/bin/env python

import subprocess
from collections import namedtuple

WifiEntry = namedtuple('WifiEntry', ['ssid', 'bssid', 'frequency', 'security'])


def populate_entry(entry):
    w = WifiEntry(ssid=entry[0][5:],
                  bssid=entry[1][6:],
                  frequency=entry[2][5:],
                  security=entry[3][9:].split(' '))
    return w


def slice_up_list(l):
    for i in range(0, len(l), 4):
        yield l[i:i+4]


def get_nw_list(nm_output):
    # turn output into a list of strings
    out = nm_output.decode('utf-8').strip('\n').split(sep='\n')
    nw_list = [populate_entry(e) for e in list(slice_up_list(out))]
    return nw_list


def get_nmcli_out(scan=None):
    rescan = "yes" if scan else "no"
    proc = subprocess.run(["nmcli", "-g", "SSID,BSSID,FREQ,SECURITY", "--mode",
                           "multiline", "device", "wifi", "list", "--rescan",
                           rescan],
                          timeout=40, check=True, stdout=subprocess.PIPE,
                          stderr=subprocess.PIPE)
    return proc.stdout


nwl = get_nw_list(get_nmcli_out())
print(nwl)
