#!/usr/bin/env fish

set ext_drive "$MEDIA/Megahulle/"

function ext_backup
    echo "Backing up to external drive..."
    rsync -rltvxP --delay-updates --delete-delay $HOME/Musik/ "$ext_drive/Gebrauch/Musik/"
    rsync -rltvxP --delay-updates $MEDIA/Erde/Backup/Musik/ "$ext_drive/Backup/Musik/"
    rsync -rltvxP --delay-updates $MEDIA/Erde/Backup/Spiele/ "$ext_drive/Backup/Spiele/"
    rsync -rltvxP --delay-updates "$MEDIA/Erde/Bilder/Ich war wo/" "$ext_drive/Backup/Bilder/"
end


function adbfs_backup
    echo "Backing up to Android device..."
    rsync -rltvxP --delay-updates --delete-delay --size-only $HOME/Musik/Singles/ "$adbfsmnt/storage/3138-3430/Music/Singles/"
    rsync -rltvxP --delay-updates --delete-delay --size-only $HOME/Musik/Alben/ "$adbfsmnt/storage/3138-3430/Music/Alben/"
end


[ -d $ext_drive ]; and ext_backup
[ -d $adbfsmnt ]; and adbfs_backup
