#!/bin/bash

echo -e "This script assumes the following:\n"\
"  - all the system's partitions are properly mounted\n"\
"  - you're in an arch-chroot\n"\
"  - the following packages are installed: linux*, linux*-firmware, base\n"\
"  - an accurate fstab exists at /etc/fstab"
read -p "Continue? [y] " answer
if [[ ! $(echo "$answer" | tr 'Y' 'y') == "y" ]]; then
	exit
fi

echo "Setting the timezone."
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
hwclock --systohc

echo "Setting de_DE and en_US locale."
sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
sed -i 's/#de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
echo "LANG=de_DE.UTF-8" > /etc/locale.conf
echo "KEYMAP=de-latin1-nodeadkeys" > /etc/vconsole.conf

read -p "Select a hostname: " myhostname
echo "Writing to /etc/hostname and /etc/hosts."
echo "$myhostname" > /etc/hostname
echo -e "127.0.0.1	localhost\n"\
"::1		localhost\n"\
"127.0.1.1	$myhostname.localdomain	$myhostname" > /etc/hosts

echo "Installing some very basic packages."
pacman -S neovim man-db man-pages

passwd

echo
echo -e "Alright. Left to do:\n"\
"  - install a bootloader\n"\
"  - create a new initramfs (if necessary)\n"\
"  - setup network for the new system"
