#!/usr/bin/env fish

function install_cower
    cd $tmp_dir
    git clone 'https://aur.archlinux.org/cower.git'
    cd cower
    makepkg -sri
    cd $tmp_dir
    rm -rf cower
end

# some AUR stuff, if it's not installed already
which cower > /dev/null 2>/dev/null; or install_cower
which nextcloud > /dev/null 2>/dev/null; or cowmake nextcloud-client
which i3 > /dev/null 2>/dev/null; or cowmake i3-gaps
which unclutter > /dev/null 2>/dev/null; or cowmake unclutter-xfixes-git

# some basic packages and globally acessible fonts
sudo pacman -S --needed \
    openssh \
    numlockx \
    firejail \
    fzf \
    feh \
    compton \
    termite \
    pass \
    unzip \
    ttf-liberation \
    noto-fonts-cjk \
    ttf-freefont \
    ttf-font-awesome \
     
# move to base directory
set -l tmp_dir (mktemp -d)
cd $tmp_dir

# install fonts from Google
curl -O -J 'https://fonts.google.com/download?family=Quicksand|Merriweather|Source%20Code%20Pro'
unzip fonts.zip
for dir in (glob -d)
    cd $dir
    cp *.ttf $HOME/.local/share/fonts
    cd $tmp_dir
end
rm -r *

# powerlinesymbols
curl -O -J 'https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf'
mv PowerlineSymbols.otf $HOME/.local/share/fonts

# install mononoki font
git clone 'https://github.com/madmalik/mononoki.git'
cd mononoki/export
unzip mononoki.zip
cp *.ttf $HOME/.local/share/fonts
cd $tmp_dir
rm -rf *

# setup firejail
sudo firecfg
sudo rm /usr/bin/local/ssh-agent

# finally, merge configs
merge_configs

echo -e "\nLeft to do:"
echo -e "\tSet-up password store"
echo -e "\tSet-up GPG"
echo -e "\tSet-up SSH"
echo -e "\tSet-up Nextcloud"
